---

- name: Install Logwatch
  apt: pkg=logwatch state=installed

- name: Email log summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
              state=present create=yes

- name: Deploy SSH Public Keys to -> {{ ansible_user }}
  authorized_key:
      user="{{ ansible_user }}"
      key="{{ item }}"
  with_items: "{{ ssh_authorized_keys }}"
  ignore_errors: False
  become: yes
  become_user: "{{ ansible_user }}"
  register: ssh_public_keys

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh
  when: disallow_password_authentication and ssh_public_keys

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart ssh
  when: disallow_root_ssh_login and ssh_public_keys

- name: Deploy Fail2Ban Odoo Config
  template:
    src: fail2ban_odoo.conf.j2
    dest: "/etc/fail2ban/filter.d/odoo.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags:
    - fail2ban
